version: 2
jobs:
    build:
        docker:
            - image: circleci/node:11.7
        steps:
            - checkout
            - run: echo "changing to client"
            - run: cd client
            - run: echo "npm installing"
            - run: npm install
            - run: npm run build
    test:
        docker:
            - image: circleci/node:11.7
        steps:
            - checkout
            - run: echo "changing to client"
            - run: cd client
            - run: echo "npm testing"
            - run: npm install
            - run: npm run test
workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - test
